//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18051.
// 
#pragma warning disable 1591

namespace Raymark.APIWebServiceTest.Raymark.APIWebReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ClientWebServiceSoap", Namespace="http://retaligent.com/Retaligent.APIWebServices/ClientWebService")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RetaligentBaseClass))]
    public partial class ClientWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SearchClientsByPhoneNumberOperationCompleted;
        
        private System.Threading.SendOrPostCallback SearchClientsByAccountNumberOperationCompleted;
        
        private System.Threading.SendOrPostCallback SearchClientsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetClientDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetClientAddressesAndPhoneNumbersOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetClientEmailAddressesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetClientAccountNumbersOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetClientEventsOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddClientOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetClientEmailAddressesForPOSOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateClientEmailAddressOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateClientEmailAddress2OperationCompleted;
        
        private System.Threading.SendOrPostCallback AddClientEmailAddressOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddClientEmailAddress2OperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ClientWebService() {
            this.Url = global::Raymark.APIWebServiceTest.Properties.Settings.Default.Raymark_APIWebServiceTest_Raymark_APIWebReference_ClientWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SearchClientsByPhoneNumberCompletedEventHandler SearchClientsByPhoneNumberCompleted;
        
        /// <remarks/>
        public event SearchClientsByAccountNumberCompletedEventHandler SearchClientsByAccountNumberCompleted;
        
        /// <remarks/>
        public event SearchClientsCompletedEventHandler SearchClientsCompleted;
        
        /// <remarks/>
        public event GetClientDetailsCompletedEventHandler GetClientDetailsCompleted;
        
        /// <remarks/>
        public event GetClientAddressesAndPhoneNumbersCompletedEventHandler GetClientAddressesAndPhoneNumbersCompleted;
        
        /// <remarks/>
        public event GetClientEmailAddressesCompletedEventHandler GetClientEmailAddressesCompleted;
        
        /// <remarks/>
        public event GetClientAccountNumbersCompletedEventHandler GetClientAccountNumbersCompleted;
        
        /// <remarks/>
        public event GetClientEventsCompletedEventHandler GetClientEventsCompleted;
        
        /// <remarks/>
        public event AddClientCompletedEventHandler AddClientCompleted;
        
        /// <remarks/>
        public event GetClientEmailAddressesForPOSCompletedEventHandler GetClientEmailAddressesForPOSCompleted;
        
        /// <remarks/>
        public event UpdateClientEmailAddressCompletedEventHandler UpdateClientEmailAddressCompleted;
        
        /// <remarks/>
        public event UpdateClientEmailAddress2CompletedEventHandler UpdateClientEmailAddress2Completed;
        
        /// <remarks/>
        public event AddClientEmailAddressCompletedEventHandler AddClientEmailAddressCompleted;
        
        /// <remarks/>
        public event AddClientEmailAddress2CompletedEventHandler AddClientEmailAddress2Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://retaligent.com/Retaligent.APIWebServices/ClientWebService/SearchClientsByP" +
            "honeNumber", RequestNamespace="http://retaligent.com/Retaligent.APIWebServices/ClientWebService", ResponseNamespace="http://retaligent.com/Retaligent.APIWebServices/ClientWebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode SearchClientsByPhoneNumber(string phoneNumber, string sortColumn, string sortOrder, int pageSize, int pageIndex) {
            object[] results = this.Invoke("SearchClientsByPhoneNumber", new object[] {
                        phoneNumber,
                        sortColumn,
                        sortOrder,
                        pageSize,
                        pageIndex});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void SearchClientsByPhoneNumberAsync(string phoneNumber, string sortColumn, string sortOrder, int pageSize, int pageIndex) {
            this.SearchClientsByPhoneNumberAsync(phoneNumber, sortColumn, sortOrder, pageSize, pageIndex, null);
        }
        
        /// <remarks/>
        public void SearchClientsByPhoneNumberAsync(string phoneNumber, string sortColumn, string sortOrder, int pageSize, int pageIndex, object userState) {
            if ((this.SearchClientsByPhoneNumberOperationCompleted == null)) {
                this.SearchClientsByPhoneNumberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchClientsByPhoneNumberOperationCompleted);
            }
            this.InvokeAsync("SearchClientsByPhoneNumber", new object[] {
                        phoneNumber,
                        sortColumn,
                        sortOrder,
                        pageSize,
                        pageIndex}, this.SearchClientsByPhoneNumberOperationCompleted, userState);
        }
        
        private void OnSearchClientsByPhoneNumberOperationCompleted(object arg) {
            if ((this.SearchClientsByPhoneNumberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchClientsByPhoneNumberCompleted(this, new SearchClientsByPhoneNumberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://retaligent.com/Retaligent.APIWebServices/ClientWebService/SearchClientsByA" +
            "ccountNumber", RequestNamespace="http://retaligent.com/Retaligent.APIWebServices/ClientWebService", ResponseNamespace="http://retaligent.com/Retaligent.APIWebServices/ClientWebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode SearchClientsByAccountNumber(string accountNumber, string sortColumn, string sortOrder, int pageSize, int pageIndex) {
            object[] results = this.Invoke("SearchClientsByAccountNumber", new object[] {
                        accountNumber,
                        sortColumn,
                        sortOrder,
                        pageSize,
                        pageIndex});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void SearchClientsByAccountNumberAsync(string accountNumber, string sortColumn, string sortOrder, int pageSize, int pageIndex) {
            this.SearchClientsByAccountNumberAsync(accountNumber, sortColumn, sortOrder, pageSize, pageIndex, null);
        }
        
        /// <remarks/>
        public void SearchClientsByAccountNumberAsync(string accountNumber, string sortColumn, string sortOrder, int pageSize, int pageIndex, object userState) {
            if ((this.SearchClientsByAccountNumberOperationCompleted == null)) {
                this.SearchClientsByAccountNumberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchClientsByAccountNumberOperationCompleted);
            }
            this.InvokeAsync("SearchClientsByAccountNumber", new object[] {
                        accountNumber,
                        sortColumn,
                        sortOrder,
                        pageSize,
                        pageIndex}, this.SearchClientsByAccountNumberOperationCompleted, userState);
        }
        
        private void OnSearchClientsByAccountNumberOperationCompleted(object arg) {
            if ((this.SearchClientsByAccountNumberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchClientsByAccountNumberCompleted(this, new SearchClientsByAccountNumberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://retaligent.com/Retaligent.APIWebServices/ClientWebService/SearchClients", RequestNamespace="http://retaligent.com/Retaligent.APIWebServices/ClientWebService", ResponseNamespace="http://retaligent.com/Retaligent.APIWebServices/ClientWebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode SearchClients(string lastName, string middleName, string firstName, string address, string city, string stateRegion, string postalCode, bool exactMatch, string sortColumn, string sortOrder, int pageSize, int pageIndex, int minimumMatchScoreThreshold) {
            object[] results = this.Invoke("SearchClients", new object[] {
                        lastName,
                        middleName,
                        firstName,
                        address,
                        city,
                        stateRegion,
                        postalCode,
                        exactMatch,
                        sortColumn,
                        sortOrder,
                        pageSize,
                        pageIndex,
                        minimumMatchScoreThreshold});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void SearchClientsAsync(string lastName, string middleName, string firstName, string address, string city, string stateRegion, string postalCode, bool exactMatch, string sortColumn, string sortOrder, int pageSize, int pageIndex, int minimumMatchScoreThreshold) {
            this.SearchClientsAsync(lastName, middleName, firstName, address, city, stateRegion, postalCode, exactMatch, sortColumn, sortOrder, pageSize, pageIndex, minimumMatchScoreThreshold, null);
        }
        
        /// <remarks/>
        public void SearchClientsAsync(string lastName, string middleName, string firstName, string address, string city, string stateRegion, string postalCode, bool exactMatch, string sortColumn, string sortOrder, int pageSize, int pageIndex, int minimumMatchScoreThreshold, object userState) {
            if ((this.SearchClientsOperationCompleted == null)) {
                this.SearchClientsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchClientsOperationCompleted);
            }
            this.InvokeAsync("SearchClients", new object[] {
                        lastName,
                        middleName,
                        firstName,
                        address,
                        city,
                        stateRegion,
                        postalCode,
                        exactMatch,
                        sortColumn,
                        sortOrder,
                        pageSize,
                        pageIndex,
                        minimumMatchScoreThreshold}, this.SearchClientsOperationCompleted, userState);
        }
        
        private void OnSearchClientsOperationCompleted(object arg) {
            if ((this.SearchClientsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchClientsCompleted(this, new SearchClientsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://retaligent.com/Retaligent.APIWebServices/ClientWebService/GetClientDetails" +
            "", RequestNamespace="http://retaligent.com/Retaligent.APIWebServices/ClientWebService", ResponseNamespace="http://retaligent.com/Retaligent.APIWebServices/ClientWebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode GetClientDetails(string clientID, bool getAddressesAndPhoneNumbers, bool getEmailAddresses, bool getEvents) {
            object[] results = this.Invoke("GetClientDetails", new object[] {
                        clientID,
                        getAddressesAndPhoneNumbers,
                        getEmailAddresses,
                        getEvents});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void GetClientDetailsAsync(string clientID, bool getAddressesAndPhoneNumbers, bool getEmailAddresses, bool getEvents) {
            this.GetClientDetailsAsync(clientID, getAddressesAndPhoneNumbers, getEmailAddresses, getEvents, null);
        }
        
        /// <remarks/>
        public void GetClientDetailsAsync(string clientID, bool getAddressesAndPhoneNumbers, bool getEmailAddresses, bool getEvents, object userState) {
            if ((this.GetClientDetailsOperationCompleted == null)) {
                this.GetClientDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetClientDetailsOperationCompleted);
            }
            this.InvokeAsync("GetClientDetails", new object[] {
                        clientID,
                        getAddressesAndPhoneNumbers,
                        getEmailAddresses,
                        getEvents}, this.GetClientDetailsOperationCompleted, userState);
        }
        
        private void OnGetClientDetailsOperationCompleted(object arg) {
            if ((this.GetClientDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetClientDetailsCompleted(this, new GetClientDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://retaligent.com/Retaligent.APIWebServices/ClientWebService/GetClientAddress" +
            "esAndPhoneNumbers", RequestNamespace="http://retaligent.com/Retaligent.APIWebServices/ClientWebService", ResponseNamespace="http://retaligent.com/Retaligent.APIWebServices/ClientWebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode GetClientAddressesAndPhoneNumbers(string clientID) {
            object[] results = this.Invoke("GetClientAddressesAndPhoneNumbers", new object[] {
                        clientID});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void GetClientAddressesAndPhoneNumbersAsync(string clientID) {
            this.GetClientAddressesAndPhoneNumbersAsync(clientID, null);
        }
        
        /// <remarks/>
        public void GetClientAddressesAndPhoneNumbersAsync(string clientID, object userState) {
            if ((this.GetClientAddressesAndPhoneNumbersOperationCompleted == null)) {
                this.GetClientAddressesAndPhoneNumbersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetClientAddressesAndPhoneNumbersOperationCompleted);
            }
            this.InvokeAsync("GetClientAddressesAndPhoneNumbers", new object[] {
                        clientID}, this.GetClientAddressesAndPhoneNumbersOperationCompleted, userState);
        }
        
        private void OnGetClientAddressesAndPhoneNumbersOperationCompleted(object arg) {
            if ((this.GetClientAddressesAndPhoneNumbersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetClientAddressesAndPhoneNumbersCompleted(this, new GetClientAddressesAndPhoneNumbersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://retaligent.com/Retaligent.APIWebServices/ClientWebService/GetClientEmailAd" +
            "dresses", RequestNamespace="http://retaligent.com/Retaligent.APIWebServices/ClientWebService", ResponseNamespace="http://retaligent.com/Retaligent.APIWebServices/ClientWebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode GetClientEmailAddresses(string clientID) {
            object[] results = this.Invoke("GetClientEmailAddresses", new object[] {
                        clientID});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void GetClientEmailAddressesAsync(string clientID) {
            this.GetClientEmailAddressesAsync(clientID, null);
        }
        
        /// <remarks/>
        public void GetClientEmailAddressesAsync(string clientID, object userState) {
            if ((this.GetClientEmailAddressesOperationCompleted == null)) {
                this.GetClientEmailAddressesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetClientEmailAddressesOperationCompleted);
            }
            this.InvokeAsync("GetClientEmailAddresses", new object[] {
                        clientID}, this.GetClientEmailAddressesOperationCompleted, userState);
        }
        
        private void OnGetClientEmailAddressesOperationCompleted(object arg) {
            if ((this.GetClientEmailAddressesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetClientEmailAddressesCompleted(this, new GetClientEmailAddressesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://retaligent.com/Retaligent.APIWebServices/ClientWebService/GetClientAccount" +
            "Numbers", RequestNamespace="http://retaligent.com/Retaligent.APIWebServices/ClientWebService", ResponseNamespace="http://retaligent.com/Retaligent.APIWebServices/ClientWebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode GetClientAccountNumbers(string clientID) {
            object[] results = this.Invoke("GetClientAccountNumbers", new object[] {
                        clientID});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void GetClientAccountNumbersAsync(string clientID) {
            this.GetClientAccountNumbersAsync(clientID, null);
        }
        
        /// <remarks/>
        public void GetClientAccountNumbersAsync(string clientID, object userState) {
            if ((this.GetClientAccountNumbersOperationCompleted == null)) {
                this.GetClientAccountNumbersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetClientAccountNumbersOperationCompleted);
            }
            this.InvokeAsync("GetClientAccountNumbers", new object[] {
                        clientID}, this.GetClientAccountNumbersOperationCompleted, userState);
        }
        
        private void OnGetClientAccountNumbersOperationCompleted(object arg) {
            if ((this.GetClientAccountNumbersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetClientAccountNumbersCompleted(this, new GetClientAccountNumbersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://retaligent.com/Retaligent.APIWebServices/ClientWebService/GetClientEvents", RequestNamespace="http://retaligent.com/Retaligent.APIWebServices/ClientWebService", ResponseNamespace="http://retaligent.com/Retaligent.APIWebServices/ClientWebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode GetClientEvents(string clientID) {
            object[] results = this.Invoke("GetClientEvents", new object[] {
                        clientID});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void GetClientEventsAsync(string clientID) {
            this.GetClientEventsAsync(clientID, null);
        }
        
        /// <remarks/>
        public void GetClientEventsAsync(string clientID, object userState) {
            if ((this.GetClientEventsOperationCompleted == null)) {
                this.GetClientEventsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetClientEventsOperationCompleted);
            }
            this.InvokeAsync("GetClientEvents", new object[] {
                        clientID}, this.GetClientEventsOperationCompleted, userState);
        }
        
        private void OnGetClientEventsOperationCompleted(object arg) {
            if ((this.GetClientEventsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetClientEventsCompleted(this, new GetClientEventsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://retaligent.com/Retaligent.APIWebServices/ClientWebService/AddClient", RequestNamespace="http://retaligent.com/Retaligent.APIWebServices/ClientWebService", ResponseNamespace="http://retaligent.com/Retaligent.APIWebServices/ClientWebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode AddClient(string xmlInput) {
            object[] results = this.Invoke("AddClient", new object[] {
                        xmlInput});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void AddClientAsync(string xmlInput) {
            this.AddClientAsync(xmlInput, null);
        }
        
        /// <remarks/>
        public void AddClientAsync(string xmlInput, object userState) {
            if ((this.AddClientOperationCompleted == null)) {
                this.AddClientOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddClientOperationCompleted);
            }
            this.InvokeAsync("AddClient", new object[] {
                        xmlInput}, this.AddClientOperationCompleted, userState);
        }
        
        private void OnAddClientOperationCompleted(object arg) {
            if ((this.AddClientCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddClientCompleted(this, new AddClientCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://retaligent.com/Retaligent.APIWebServices/ClientWebService/GetClientEmailAd" +
            "dressesForPOS", RequestNamespace="http://retaligent.com/Retaligent.APIWebServices/ClientWebService", ResponseNamespace="http://retaligent.com/Retaligent.APIWebServices/ClientWebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode GetClientEmailAddressesForPOS(string clientID) {
            object[] results = this.Invoke("GetClientEmailAddressesForPOS", new object[] {
                        clientID});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void GetClientEmailAddressesForPOSAsync(string clientID) {
            this.GetClientEmailAddressesForPOSAsync(clientID, null);
        }
        
        /// <remarks/>
        public void GetClientEmailAddressesForPOSAsync(string clientID, object userState) {
            if ((this.GetClientEmailAddressesForPOSOperationCompleted == null)) {
                this.GetClientEmailAddressesForPOSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetClientEmailAddressesForPOSOperationCompleted);
            }
            this.InvokeAsync("GetClientEmailAddressesForPOS", new object[] {
                        clientID}, this.GetClientEmailAddressesForPOSOperationCompleted, userState);
        }
        
        private void OnGetClientEmailAddressesForPOSOperationCompleted(object arg) {
            if ((this.GetClientEmailAddressesForPOSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetClientEmailAddressesForPOSCompleted(this, new GetClientEmailAddressesForPOSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://retaligent.com/Retaligent.APIWebServices/ClientWebService/UpdateClientEmai" +
            "lAddress", RequestNamespace="http://retaligent.com/Retaligent.APIWebServices/ClientWebService", ResponseNamespace="http://retaligent.com/Retaligent.APIWebServices/ClientWebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode UpdateClientEmailAddress(string clientID, string emailGuid, string associateID, string emailAddress) {
            object[] results = this.Invoke("UpdateClientEmailAddress", new object[] {
                        clientID,
                        emailGuid,
                        associateID,
                        emailAddress});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateClientEmailAddressAsync(string clientID, string emailGuid, string associateID, string emailAddress) {
            this.UpdateClientEmailAddressAsync(clientID, emailGuid, associateID, emailAddress, null);
        }
        
        /// <remarks/>
        public void UpdateClientEmailAddressAsync(string clientID, string emailGuid, string associateID, string emailAddress, object userState) {
            if ((this.UpdateClientEmailAddressOperationCompleted == null)) {
                this.UpdateClientEmailAddressOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateClientEmailAddressOperationCompleted);
            }
            this.InvokeAsync("UpdateClientEmailAddress", new object[] {
                        clientID,
                        emailGuid,
                        associateID,
                        emailAddress}, this.UpdateClientEmailAddressOperationCompleted, userState);
        }
        
        private void OnUpdateClientEmailAddressOperationCompleted(object arg) {
            if ((this.UpdateClientEmailAddressCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateClientEmailAddressCompleted(this, new UpdateClientEmailAddressCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://retaligent.com/Retaligent.APIWebServices/ClientWebService/UpdateClientEmai" +
            "lAddress2", RequestNamespace="http://retaligent.com/Retaligent.APIWebServices/ClientWebService", ResponseNamespace="http://retaligent.com/Retaligent.APIWebServices/ClientWebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode UpdateClientEmailAddress2(string clientID, string associateID, EmailAddress emailAddress) {
            object[] results = this.Invoke("UpdateClientEmailAddress2", new object[] {
                        clientID,
                        associateID,
                        emailAddress});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateClientEmailAddress2Async(string clientID, string associateID, EmailAddress emailAddress) {
            this.UpdateClientEmailAddress2Async(clientID, associateID, emailAddress, null);
        }
        
        /// <remarks/>
        public void UpdateClientEmailAddress2Async(string clientID, string associateID, EmailAddress emailAddress, object userState) {
            if ((this.UpdateClientEmailAddress2OperationCompleted == null)) {
                this.UpdateClientEmailAddress2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateClientEmailAddress2OperationCompleted);
            }
            this.InvokeAsync("UpdateClientEmailAddress2", new object[] {
                        clientID,
                        associateID,
                        emailAddress}, this.UpdateClientEmailAddress2OperationCompleted, userState);
        }
        
        private void OnUpdateClientEmailAddress2OperationCompleted(object arg) {
            if ((this.UpdateClientEmailAddress2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateClientEmailAddress2Completed(this, new UpdateClientEmailAddress2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://retaligent.com/Retaligent.APIWebServices/ClientWebService/AddClientEmailAd" +
            "dress", RequestNamespace="http://retaligent.com/Retaligent.APIWebServices/ClientWebService", ResponseNamespace="http://retaligent.com/Retaligent.APIWebServices/ClientWebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode AddClientEmailAddress(string clientID, string associateID, string emailAddress) {
            object[] results = this.Invoke("AddClientEmailAddress", new object[] {
                        clientID,
                        associateID,
                        emailAddress});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void AddClientEmailAddressAsync(string clientID, string associateID, string emailAddress) {
            this.AddClientEmailAddressAsync(clientID, associateID, emailAddress, null);
        }
        
        /// <remarks/>
        public void AddClientEmailAddressAsync(string clientID, string associateID, string emailAddress, object userState) {
            if ((this.AddClientEmailAddressOperationCompleted == null)) {
                this.AddClientEmailAddressOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddClientEmailAddressOperationCompleted);
            }
            this.InvokeAsync("AddClientEmailAddress", new object[] {
                        clientID,
                        associateID,
                        emailAddress}, this.AddClientEmailAddressOperationCompleted, userState);
        }
        
        private void OnAddClientEmailAddressOperationCompleted(object arg) {
            if ((this.AddClientEmailAddressCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddClientEmailAddressCompleted(this, new AddClientEmailAddressCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://retaligent.com/Retaligent.APIWebServices/ClientWebService/AddClientEmailAd" +
            "dress2", RequestNamespace="http://retaligent.com/Retaligent.APIWebServices/ClientWebService", ResponseNamespace="http://retaligent.com/Retaligent.APIWebServices/ClientWebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode AddClientEmailAddress2(string clientID, string associateID, EmailAddress emailAddress) {
            object[] results = this.Invoke("AddClientEmailAddress2", new object[] {
                        clientID,
                        associateID,
                        emailAddress});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void AddClientEmailAddress2Async(string clientID, string associateID, EmailAddress emailAddress) {
            this.AddClientEmailAddress2Async(clientID, associateID, emailAddress, null);
        }
        
        /// <remarks/>
        public void AddClientEmailAddress2Async(string clientID, string associateID, EmailAddress emailAddress, object userState) {
            if ((this.AddClientEmailAddress2OperationCompleted == null)) {
                this.AddClientEmailAddress2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddClientEmailAddress2OperationCompleted);
            }
            this.InvokeAsync("AddClientEmailAddress2", new object[] {
                        clientID,
                        associateID,
                        emailAddress}, this.AddClientEmailAddress2OperationCompleted, userState);
        }
        
        private void OnAddClientEmailAddress2OperationCompleted(object arg) {
            if ((this.AddClientEmailAddress2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddClientEmailAddress2Completed(this, new AddClientEmailAddress2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://retaligent.com/Retaligent.APIWebServices/ClientWebService")]
    public partial class EmailAddress : RetaligentBaseClass {
        
        private string addressField;
        
        private string descriptionField;
        
        private TypeCode typeEmailField;
        
        private EmailPermissionLevel emailPermissionField;
        
        private bool canContactField;
        
        private bool isPreferredEmailField;
        
        /// <remarks/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public TypeCode TypeEmail {
            get {
                return this.typeEmailField;
            }
            set {
                this.typeEmailField = value;
            }
        }
        
        /// <remarks/>
        public EmailPermissionLevel EmailPermission {
            get {
                return this.emailPermissionField;
            }
            set {
                this.emailPermissionField = value;
            }
        }
        
        /// <remarks/>
        public bool CanContact {
            get {
                return this.canContactField;
            }
            set {
                this.canContactField = value;
            }
        }
        
        /// <remarks/>
        public bool IsPreferredEmail {
            get {
                return this.isPreferredEmailField;
            }
            set {
                this.isPreferredEmailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ListData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Role))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://retaligent.com/Retaligent.APIWebServices/ClientWebService")]
    public partial class TypeCode {
        
        private int typeIDIntField;
        
        private System.Guid typeIDField;
        
        private string typeSpecifierField;
        
        private string typeDescriptionField;
        
        private int typePrecedenceField;
        
        private RecordState rowStateField;
        
        /// <remarks/>
        public int TypeIDInt {
            get {
                return this.typeIDIntField;
            }
            set {
                this.typeIDIntField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid TypeID {
            get {
                return this.typeIDField;
            }
            set {
                this.typeIDField = value;
            }
        }
        
        /// <remarks/>
        public string TypeSpecifier {
            get {
                return this.typeSpecifierField;
            }
            set {
                this.typeSpecifierField = value;
            }
        }
        
        /// <remarks/>
        public string TypeDescription {
            get {
                return this.typeDescriptionField;
            }
            set {
                this.typeDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public int TypePrecedence {
            get {
                return this.typePrecedenceField;
            }
            set {
                this.typePrecedenceField = value;
            }
        }
        
        /// <remarks/>
        public RecordState RowState {
            get {
                return this.rowStateField;
            }
            set {
                this.rowStateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://retaligent.com/Retaligent.APIWebServices/ClientWebService")]
    public enum RecordState {
        
        /// <remarks/>
        Unchanged,
        
        /// <remarks/>
        Inserted,
        
        /// <remarks/>
        Updated,
        
        /// <remarks/>
        Deleted,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ListDataItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EmailAddress))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://retaligent.com/Retaligent.APIWebServices/ClientWebService")]
    public abstract partial class RetaligentBaseClass {
        
        private System.DateTime lastUpdatedField;
        
        private RecordState rowStateField;
        
        private System.Guid idField;
        
        private byte[] lastGuidField;
        
        /// <remarks/>
        public System.DateTime LastUpdated {
            get {
                return this.lastUpdatedField;
            }
            set {
                this.lastUpdatedField = value;
            }
        }
        
        /// <remarks/>
        public RecordState RowState {
            get {
                return this.rowStateField;
            }
            set {
                this.rowStateField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] LastGuid {
            get {
                return this.lastGuidField;
            }
            set {
                this.lastGuidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://retaligent.com/Retaligent.APIWebServices/ClientWebService")]
    public partial class ListDataItem : RetaligentBaseClass {
        
        private System.Guid typeIDField;
        
        private string itemDescriptionField;
        
        /// <remarks/>
        public System.Guid TypeID {
            get {
                return this.typeIDField;
            }
            set {
                this.typeIDField = value;
            }
        }
        
        /// <remarks/>
        public string ItemDescription {
            get {
                return this.itemDescriptionField;
            }
            set {
                this.itemDescriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://retaligent.com/Retaligent.APIWebServices/ClientWebService")]
    public partial class ListData : TypeCode {
        
        private ListDataItem[] listItemsField;
        
        /// <remarks/>
        public ListDataItem[] ListItems {
            get {
                return this.listItemsField;
            }
            set {
                this.listItemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://retaligent.com/Retaligent.APIWebServices/ClientWebService")]
    public partial class Role : TypeCode {
        
        private TypeCode[] permissionsField;
        
        private TypeCode typeUserField;
        
        private string roleIDField;
        
        private string roleIDIntField;
        
        /// <remarks/>
        public TypeCode[] Permissions {
            get {
                return this.permissionsField;
            }
            set {
                this.permissionsField = value;
            }
        }
        
        /// <remarks/>
        public TypeCode TypeUser {
            get {
                return this.typeUserField;
            }
            set {
                this.typeUserField = value;
            }
        }
        
        /// <remarks/>
        public string RoleID {
            get {
                return this.roleIDField;
            }
            set {
                this.roleIDField = value;
            }
        }
        
        /// <remarks/>
        public string RoleIDInt {
            get {
                return this.roleIDIntField;
            }
            set {
                this.roleIDIntField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://retaligent.com/Retaligent.APIWebServices/ClientWebService")]
    public enum EmailPermissionLevel {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        Receipt,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void SearchClientsByPhoneNumberCompletedEventHandler(object sender, SearchClientsByPhoneNumberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchClientsByPhoneNumberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchClientsByPhoneNumberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void SearchClientsByAccountNumberCompletedEventHandler(object sender, SearchClientsByAccountNumberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchClientsByAccountNumberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchClientsByAccountNumberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void SearchClientsCompletedEventHandler(object sender, SearchClientsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchClientsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchClientsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetClientDetailsCompletedEventHandler(object sender, GetClientDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetClientDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetClientDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetClientAddressesAndPhoneNumbersCompletedEventHandler(object sender, GetClientAddressesAndPhoneNumbersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetClientAddressesAndPhoneNumbersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetClientAddressesAndPhoneNumbersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetClientEmailAddressesCompletedEventHandler(object sender, GetClientEmailAddressesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetClientEmailAddressesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetClientEmailAddressesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetClientAccountNumbersCompletedEventHandler(object sender, GetClientAccountNumbersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetClientAccountNumbersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetClientAccountNumbersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetClientEventsCompletedEventHandler(object sender, GetClientEventsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetClientEventsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetClientEventsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void AddClientCompletedEventHandler(object sender, AddClientCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddClientCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddClientCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetClientEmailAddressesForPOSCompletedEventHandler(object sender, GetClientEmailAddressesForPOSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetClientEmailAddressesForPOSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetClientEmailAddressesForPOSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void UpdateClientEmailAddressCompletedEventHandler(object sender, UpdateClientEmailAddressCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateClientEmailAddressCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateClientEmailAddressCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void UpdateClientEmailAddress2CompletedEventHandler(object sender, UpdateClientEmailAddress2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateClientEmailAddress2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateClientEmailAddress2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void AddClientEmailAddressCompletedEventHandler(object sender, AddClientEmailAddressCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddClientEmailAddressCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddClientEmailAddressCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void AddClientEmailAddress2CompletedEventHandler(object sender, AddClientEmailAddress2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddClientEmailAddress2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddClientEmailAddress2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591