//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mi9.Store.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mi9.Store.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t make balance. There is a balance already with that data..
        /// </summary>
        public static string CashManagement_BalanceAlreadyDone {
            get {
                return ResourceManager.GetString("CashManagement_BalanceAlreadyDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t make balancing in closed drawer..
        /// </summary>
        public static string CashManagement_BalancingClosedDrawer {
            get {
                return ResourceManager.GetString("CashManagement_BalancingClosedDrawer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balancing method argument not found..
        /// </summary>
        public static string CashManagement_BalancingMethodNotFound {
            get {
                return ResourceManager.GetString("CashManagement_BalancingMethodNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot deposit more than is in safe.
        /// </summary>
        public static string CashManagement_CannotDeposit {
            get {
                return ResourceManager.GetString("CashManagement_CannotDeposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not create the deposit. It already exists..
        /// </summary>
        public static string CashManagement_CannotDepositExist {
            get {
                return ResourceManager.GetString("CashManagement_CannotDepositExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot deposit. Deposit number is incorrect..
        /// </summary>
        public static string CashManagement_CannotDepositWrongNumber {
            get {
                return ResourceManager.GetString("CashManagement_CannotDepositWrongNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t change the status of the deposit..
        /// </summary>
        public static string CashManagement_CantChangeDepositStatus {
            get {
                return ResourceManager.GetString("CashManagement_CantChangeDepositStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t delete the deposit. Doesn&apos;t exist..
        /// </summary>
        public static string CashManagement_CantDeleteDepositExist {
            get {
                return ResourceManager.GetString("CashManagement_CantDeleteDepositExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t delete the deposit. No safe balance..
        /// </summary>
        public static string CashManagement_CantDeleteDepositSafe {
            get {
                return ResourceManager.GetString("CashManagement_CantDeleteDepositSafe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This deposit has been uploaded and cannot be deleted..
        /// </summary>
        public static string CashManagement_CantDeleteDepositUploaded {
            get {
                return ResourceManager.GetString("CashManagement_CantDeleteDepositUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find base currency information.
        /// </summary>
        public static string CashManagement_CantFindBaseCurrencyInformation {
            get {
                return ResourceManager.GetString("CashManagement_CantFindBaseCurrencyInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find base tender information.
        /// </summary>
        public static string CashManagement_CantFindBaseTenderInformation {
            get {
                return ResourceManager.GetString("CashManagement_CantFindBaseTenderInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find drawer balance for cashier {0} with date {1} and drawer {2}.
        /// </summary>
        public static string CashManagement_CantFindCashierDrawerBalance {
            get {
                return ResourceManager.GetString("CashManagement_CantFindCashierDrawerBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find cashier information.
        /// </summary>
        public static string CashManagement_CantFindCashierInformation {
            get {
                return ResourceManager.GetString("CashManagement_CantFindCashierInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find Cash Office configuration.
        /// </summary>
        public static string CashManagement_CantFindCashOfficeConfiguration {
            get {
                return ResourceManager.GetString("CashManagement_CantFindCashOfficeConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find information for currency with code {0} .
        /// </summary>
        public static string CashManagement_CantFindCurrencyInformation {
            get {
                return ResourceManager.GetString("CashManagement_CantFindCurrencyInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find the deposit..
        /// </summary>
        public static string CashManagement_CantFindDepositInformation {
            get {
                return ResourceManager.GetString("CashManagement_CantFindDepositInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find logged employee information.
        /// </summary>
        public static string CashManagement_CantFindLoggedEmployeeInformation {
            get {
                return ResourceManager.GetString("CashManagement_CantFindLoggedEmployeeInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find pickup.
        /// </summary>
        public static string CashManagement_CantFindPickup {
            get {
                return ResourceManager.GetString("CashManagement_CantFindPickup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find drawer balance for register {0} with date {1} and drawer {2}.
        /// </summary>
        public static string CashManagement_CantFindRegisterDrawerBalance {
            get {
                return ResourceManager.GetString("CashManagement_CantFindRegisterDrawerBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find register information.
        /// </summary>
        public static string CashManagement_CantFindRegisterInformation {
            get {
                return ResourceManager.GetString("CashManagement_CantFindRegisterInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting bank information not found. Can&apos;t make a loan without a previous starting bank.
        /// </summary>
        public static string CashManagement_CantFindStartingBankInfoToPerformLoan {
            get {
                return ResourceManager.GetString("CashManagement_CantFindStartingBankInfoToPerformLoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting bank information not found. Can&apos;t make a pickup without a previous starting bank.
        /// </summary>
        public static string CashManagement_CantFindStartingBankInfoToPerformPickup {
            get {
                return ResourceManager.GetString("CashManagement_CantFindStartingBankInfoToPerformPickup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find Store Accounting period information.
        /// </summary>
        public static string CashManagement_CantFindStoreAccountingPeriodInformation {
            get {
                return ResourceManager.GetString("CashManagement_CantFindStoreAccountingPeriodInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find store information.
        /// </summary>
        public static string CashManagement_CantFindStoreInformation {
            get {
                return ResourceManager.GetString("CashManagement_CantFindStoreInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find information for tender with code {0}.
        /// </summary>
        public static string CashManagement_CantFindTenderInformation {
            get {
                return ResourceManager.GetString("CashManagement_CantFindTenderInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t perform a pickup if drawer is not in status &apos;Issued&apos;.
        /// </summary>
        public static string CashManagement_CantPerformPickupOverDrawerIfNotIssued {
            get {
                return ResourceManager.GetString("CashManagement_CantPerformPickupOverDrawerIfNotIssued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t perform a pickup over a drawer opened on different date than active period {0}.
        /// </summary>
        public static string CashManagement_CantPerformPickupOverDrawerOpenedOtherDateThanActivePeriod {
            get {
                return ResourceManager.GetString("CashManagement_CantPerformPickupOverDrawerOpenedOtherDateThanActivePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t update the deposit. Doesn&apos;t exist..
        /// </summary>
        public static string CashManagement_CantUpdateDepositExist {
            get {
                return ResourceManager.GetString("CashManagement_CantUpdateDepositExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This deposit has been uploaded and cannot be updated..
        /// </summary>
        public static string CashManagement_CantUpdateDepositUploaded {
            get {
                return ResourceManager.GetString("CashManagement_CantUpdateDepositUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find a cash safe record for one tender {0} and currency {1}. Please verify the audit..
        /// </summary>
        public static string CashManagement_CashSafeNotExist {
            get {
                return ResourceManager.GetString("CashManagement_CashSafeNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find a cash safe record for one tender {0} and currency {1}. Please verify the amountInSafe..
        /// </summary>
        public static string CashManagement_CashSafeNotFound {
            get {
                return ResourceManager.GetString("CashManagement_CashSafeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t make drawer balancing without make a Z-read..
        /// </summary>
        public static string CashManagement_DrawerBalancingWithoutZRead {
            get {
                return ResourceManager.GetString("CashManagement_DrawerBalancingWithoutZRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t perform loan. Drawer is closed.
        /// </summary>
        public static string CashManagement_DrawerClosed {
            get {
                return ResourceManager.GetString("CashManagement_DrawerClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t perform pickup. Drawer not open..
        /// </summary>
        public static string CashManagement_DrawerNotIssued {
            get {
                return ResourceManager.GetString("CashManagement_DrawerNotIssued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t make balance. Drawer must be in Unbalanced status..
        /// </summary>
        public static string CashManagement_DrawerNotUnbalanced {
            get {
                return ResourceManager.GetString("CashManagement_DrawerNotUnbalanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t issue loan. ZRead already done. Drawer is ready for balance.
        /// </summary>
        public static string CashManagement_DrawerUnbalanced {
            get {
                return ResourceManager.GetString("CashManagement_DrawerUnbalanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input pick up. Duplicated key &lt;TenderId, CurrencyId&gt;.
        /// </summary>
        public static string CashManagement_DuplicatedTenderCurrencyId {
            get {
                return ResourceManager.GetString("CashManagement_DuplicatedTenderCurrencyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount must be greater than 0..
        /// </summary>
        public static string CashManagement_InvalidAmount {
            get {
                return ResourceManager.GetString("CashManagement_InvalidAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Balancing Method..
        /// </summary>
        public static string CashManagement_InvalidBalancingMethod {
            get {
                return ResourceManager.GetString("CashManagement_InvalidBalancingMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Cashier..
        /// </summary>
        public static string CashManagement_InvalidCashierId {
            get {
                return ResourceManager.GetString("CashManagement_InvalidCashierId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawer number must be between 1 and 3..
        /// </summary>
        public static string CashManagement_InvalidDrawerNumber {
            get {
                return ResourceManager.GetString("CashManagement_InvalidDrawerNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid loan parameters. There is not information to create the loan.
        /// </summary>
        public static string CashManagement_InvalidLoanParameters {
            get {
                return ResourceManager.GetString("CashManagement_InvalidLoanParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Loan Type..
        /// </summary>
        public static string CashManagement_InvalidLoanType {
            get {
                return ResourceManager.GetString("CashManagement_InvalidLoanType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid pickup parameters. There is not information to create the pickup.
        /// </summary>
        public static string CashManagement_InvalidPickupParameters {
            get {
                return ResourceManager.GetString("CashManagement_InvalidPickupParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Register Id..
        /// </summary>
        public static string CashManagement_InvalidRegisterId {
            get {
                return ResourceManager.GetString("CashManagement_InvalidRegisterId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawer balancing information not found..
        /// </summary>
        public static string CashManagement_NotDrawerInfo {
            get {
                return ResourceManager.GetString("CashManagement_NotDrawerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough sufficient funds in safe to delete the pickup.
        /// </summary>
        public static string CashManagement_NotEnoughFundsForDeletePickup {
            get {
                return ResourceManager.GetString("CashManagement_NotEnoughFundsForDeletePickup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough funds in safe to perform a loan.
        /// </summary>
        public static string CashManagement_NotEnoughFundsForLoan {
            get {
                return ResourceManager.GetString("CashManagement_NotEnoughFundsForLoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current balance is not enough to perform a pickup for tender: {0} ({1}).
        /// </summary>
        public static string CashManagement_NotEnoughFundsForPickup {
            get {
                return ResourceManager.GetString("CashManagement_NotEnoughFundsForPickup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough funds in safe to issue a starting bank.
        /// </summary>
        public static string CashManagement_NotEnoughFundsForStartingBank {
            get {
                return ResourceManager.GetString("CashManagement_NotEnoughFundsForStartingBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Please reload page..
        /// </summary>
        public static string CashManagement_SomethingWrong {
            get {
                return ResourceManager.GetString("CashManagement_SomethingWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Bank already exists for cashier {0} with date {1} and drawer {2}.
        /// </summary>
        public static string CashManagement_StartingBankAlreadyCreatedForCashier {
            get {
                return ResourceManager.GetString("CashManagement_StartingBankAlreadyCreatedForCashier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Bank already exists for register {0} with date {1} and drawer {2}.
        /// </summary>
        public static string CashManagement_StartingBankAlreadyCreatedForRegister {
            get {
                return ResourceManager.GetString("CashManagement_StartingBankAlreadyCreatedForRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t create employee request absence.
        /// </summary>
        public static string LaborManagement_Maintenance_CantCreateEmployeeRequestAbsence {
            get {
                return ResourceManager.GetString("LaborManagement_Maintenance_CantCreateEmployeeRequestAbsence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t create this request absence because will create an overlapping with existing request absence.
        /// </summary>
        public static string LaborManagement_Maintenance_CantCreateRequestAbsenceDueToOverlappingRequestAbsence {
            get {
                return ResourceManager.GetString("LaborManagement_Maintenance_CantCreateRequestAbsenceDueToOverlappingRequestAbsenc" +
                        "e", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t create this training day because will create an overlapping with existing request absence.
        /// </summary>
        public static string LaborManagement_Maintenance_CantCreateTrainingDayRequestDueToOverlappingRequestAbsence {
            get {
                return ResourceManager.GetString("LaborManagement_Maintenance_CantCreateTrainingDayRequestDueToOverlappingRequestAb" +
                        "sence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find employee.
        /// </summary>
        public static string LaborManagement_Maintenance_CantFidEmployee {
            get {
                return ResourceManager.GetString("LaborManagement_Maintenance_CantFidEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t update employee request absence.
        /// </summary>
        public static string LaborManagement_Maintenance_CantUpdateEmployeeRequestAbsence {
            get {
                return ResourceManager.GetString("LaborManagement_Maintenance_CantUpdateEmployeeRequestAbsence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t update GeneratedScheduleDays and Training Day at the same time.
        /// </summary>
        public static string LaborManagement_Maintenance_CantUpdateGeneratedScheduleDaysAndTrainingDayAtSameTime {
            get {
                return ResourceManager.GetString("LaborManagement_Maintenance_CantUpdateGeneratedScheduleDaysAndTrainingDayAtSameTi" +
                        "me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t update this request absence because will create an overlapping with existing request absence.
        /// </summary>
        public static string LaborManagement_Maintenance_CantUpdateRequestAbsenceDueToOverlappingRequestAbsence {
            get {
                return ResourceManager.GetString("LaborManagement_Maintenance_CantUpdateRequestAbsenceDueToOverlappingRequestAbsenc" +
                        "e", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t update this training day because will create an overlapping with existing request absence.
        /// </summary>
        public static string LaborManagement_Maintenance_CantUpdateTrainingDayRequestDueToOverlappingRequestAbsence {
            get {
                return ResourceManager.GetString("LaborManagement_Maintenance_CantUpdateTrainingDayRequestDueToOverlappingRequestAb" +
                        "sence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mms didn&apos;t find data for this sku.
        /// </summary>
        public static string MmsEmptyXml {
            get {
                return ResourceManager.GetString("MmsEmptyXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pallet not found.
        /// </summary>
        public static string Pallet_Not_Found {
            get {
                return ResourceManager.GetString("Pallet_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Price.
        /// </summary>
        public static string PendingPrice {
            get {
                return ResourceManager.GetString("PendingPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete PreCount Scheduler.
        /// </summary>
        public static string PhyInvPreCountSchedDeleteError {
            get {
                return ResourceManager.GetString("PhyInvPreCountSchedDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a Physical Inventory with the same Start Date: .
        /// </summary>
        public static string PhysicalInventoryDuplicatedError {
            get {
                return ResourceManager.GetString("PhysicalInventoryDuplicatedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find a Physical Inventory..
        /// </summary>
        public static string PhysicalInventoryNotFound {
            get {
                return ResourceManager.GetString("PhysicalInventoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find a Register..
        /// </summary>
        public static string RegisterNotFound {
            get {
                return ResourceManager.GetString("RegisterNotFound", resourceCulture);
            }
        }
    }
}
