//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mi9.Store.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mi9.Store.Localization.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance date can not be in future..
        /// </summary>
        public static string AttendanceDateInFuture {
            get {
                return ResourceManager.GetString("AttendanceDateInFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance date is required field..
        /// </summary>
        public static string AttendanceDateMinValue {
            get {
                return ResourceManager.GetString("AttendanceDateMinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not set date in future..
        /// </summary>
        public static string DateInFuture {
            get {
                return ResourceManager.GetString("DateInFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date must be great than.
        /// </summary>
        public static string DateSqlMin {
            get {
                return ResourceManager.GetString("DateSqlMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmployeeNo is incorrect..
        /// </summary>
        public static string EmployeeNoIncorrect {
            get {
                return ResourceManager.GetString("EmployeeNoIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee number and employee entity are not consistent..
        /// </summary>
        public static string EmployeeNumberNotConsistent {
            get {
                return ResourceManager.GetString("EmployeeNumberNotConsistent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intervals earlier than the last in the list are not allowed..
        /// </summary>
        public static string IntervalEarlyThenLastInList {
            get {
                return ResourceManager.GetString("IntervalEarlyThenLastInList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval must be more than one minute..
        /// </summary>
        public static string IntervalIsEmpty {
            get {
                return ResourceManager.GetString("IntervalIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intervals is required field..
        /// </summary>
        public static string IntervalsNull {
            get {
                return ResourceManager.GetString("IntervalsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not add a multiple open intervals..
        /// </summary>
        public static string MultipleOpenInterval {
            get {
                return ResourceManager.GetString("MultipleOpenInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not add multiple overnight intervals..
        /// </summary>
        public static string MultipleOvernightIntervals {
            get {
                return ResourceManager.GetString("MultipleOvernightIntervals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New interval cannot be added, when the current list has an open interval..
        /// </summary>
        public static string OpenIntervalIsLastInList {
            get {
                return ResourceManager.GetString("OpenIntervalIsLastInList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlapped intervals are not allowed..
        /// </summary>
        public static string OverlappedIntervals {
            get {
                return ResourceManager.GetString("OverlappedIntervals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total hours exceed the limit value..
        /// </summary>
        public static string TotalHoursExceedLimit {
            get {
                return ResourceManager.GetString("TotalHoursExceedLimit", resourceCulture);
            }
        }
    }
}
